# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

sudo: required

r_packages:
  - covr
  - devtools

r_github_packages:
  - xiayh17/CP2S

after_success:
  - Rscript -e 'library(covr);codecov()'