# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

language: r

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  CODECOV_TOKEN='d705382d-da7b-4552-9d11-caa8151d1c54'